os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
jobs:
  include:
    - stage: Test
      language: dart
      dart_task:
      - test: --platform vm
      - dartfmt: true
      before_script:
        # file names are not allowed to include capital letters
        - chmod 777 ./.no_camel.sh
        - ./.no_camel.sh
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - ./flutter/bin/flutter analyze
      script:
        - ./flutter/bin/flutter test
    - stage: Deploy
      if: branch = master
      language: android
      android:
        components:
          # The BuildTools version used by your project
          - build-tools-27.0.2
          # The SDK version used to compile your project
          - android-27
          # Sys image for eventual virtual devices
          - sys-img-armeabi-v7a-android-26
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      before_script:
        - ../flutter/bin/flutter doctor
      script:
        - ../flutter/bin/flutter -v build apk
cache:
  directories:
  - $HOME/.pub-cache
