os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
jobs:
  include:
    - stage: Test
      language: general
      before_script:
        - git clone https://github.com/flutter/flutter.git ../flutter -b beta --depth 1
        - ../flutter/bin/flutter doctor
        - chmod 777 ./.no_camel.sh
        - ./.no_camel.sh # file names are not allowed to include capital letters
        - $(../flutter/bin/cache/dart-sdk/bin/dartfmt -n lib) # check if files are formatted according to dartfmt
        - gem install coveralls-lcov
      script:
        - ../flutter/bin/flutter analyze
        - ../flutter/bin/flutter test --coverage test/*
      after_success:
        - coveralls-lcov coverage/lcov.info
    - stage: Deploy
      if: branch = travis-test
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - sys-img-armeabi-v7a-google_apis-27
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      jdk: oraclejdk8
      before_script:
        - git clone https://github.com/flutter/flutter.git ../flutter -b beta --depth 1
        - yes|/usr/local/android-sdk/tools/bin/sdkmanager --update
        - ../flutter/bin/flutter doctor --android-licenses
      script:
        - ../flutter/bin/flutter -v build apk
      before_deploy:
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
        - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
        - git push -q https://$TAGPERM@github.com/mobileappdevhm/team2 --tags
        - ls -R
      deploy:
        provider: releases
        api_key: ${GithubToken}
        file: "/build/app/outputs/apk/release/app-release.apk"
        skip_cleanup: true
cache:
  directories:
  - $HOME/.pub-cache
