name: courses_in_english
description: A Flutter project aimed at providing additicnal functionality for international students.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.0
  sqflite: any
  path_provider: ^0.4.0
  firebase_messaging: ^0.2.4
  firebase_analytics: ^1.0.1
  cupertino_icons: ^0.1.0
  simple_permissions: any
  quiver: '>=0.29.0 <0.30.0'

  # Dependency for the search feature
  flutter_search_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

flutter:
  uses-material-design: true

  assets:
    # Cow animation
    - res/anim_cow.gif
    # Locations
    - res/location/campus_lothstr.png
    - res/location/campus_karlstr.png
    - res/location/campus_pasing.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages