name: courses_in_english
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Locations
    - res/location/campus_lothstr.png
    - res/location/campus_karlstr.png
    - res/location/campus_pasing.png
    # Cow animation images
    - res/cow-anim/frame0001.png
    - res/cow-anim/frame0002.png
    - res/cow-anim/frame0003.png
    - res/cow-anim/frame0004.png
    - res/cow-anim/frame0005.png
    - res/cow-anim/frame0006.png
    - res/cow-anim/frame0007.png
    - res/cow-anim/frame0008.png
    - res/cow-anim/frame0009.png
    - res/cow-anim/frame0010.png
    - res/cow-anim/frame0011.png
    - res/cow-anim/frame0012.png
    - res/cow-anim/frame0013.png
    - res/cow-anim/frame0014.png
    - res/cow-anim/frame0015.png
    - res/cow-anim/frame0016.png
    - res/cow-anim/frame0017.png
    - res/cow-anim/frame0018.png
    - res/cow-anim/frame0019.png
    - res/cow-anim/frame0020.png
    - res/cow-anim/frame0021.png
    - res/cow-anim/frame0022.png
    - res/cow-anim/frame0023.png
    - res/cow-anim/frame0024.png
    - res/cow-anim/frame0025.png
    - res/cow-anim/frame0026.png
    - res/cow-anim/frame0027.png
    - res/cow-anim/frame0028.png
    - res/cow-anim/frame0029.png
    - res/cow-anim/frame0030.png
    - res/cow-anim/frame0031.png
    - res/cow-anim/frame0032.png
    - res/cow-anim/frame0033.png
    - res/cow-anim/frame0034.png
    - res/cow-anim/frame0035.png
    - res/cow-anim/frame0036.png
    - res/cow-anim/frame0037.png
    - res/cow-anim/frame0038.png
    - res/cow-anim/frame0039.png
    - res/cow-anim/frame0040.png
    - res/cow-anim/frame0041.png
    - res/cow-anim/frame0042.png
    - res/cow-anim/frame0043.png
    - res/cow-anim/frame0044.png
    - res/cow-anim/frame0045.png
    - res/cow-anim/frame0046.png
    - res/cow-anim/frame0047.png
    - res/cow-anim/frame0048.png
    - res/cow-anim/frame0049.png
    - res/cow-anim/frame0050.png
    - res/cow-anim/frame0051.png
    - res/cow-anim/frame0052.png
    - res/cow-anim/frame0053.png
    - res/cow-anim/frame0054.png
    - res/cow-anim/frame0055.png
    - res/cow-anim/frame0056.png
    - res/cow-anim/frame0057.png
    - res/cow-anim/frame0058.png
    - res/cow-anim/frame0059.png
    - res/cow-anim/frame0060.png
    - res/cow-anim/frame0061.png
    - res/cow-anim/frame0062.png
    - res/cow-anim/frame0063.png
    - res/cow-anim/frame0064.png
    - res/cow-anim/frame0065.png
    - res/cow-anim/frame0066.png
    - res/cow-anim/frame0067.png
    - res/cow-anim/frame0068.png
    - res/cow-anim/frame0069.png
    - res/cow-anim/frame0070.png
    - res/cow-anim/frame0071.png
    - res/cow-anim/frame0072.png
    - res/cow-anim/frame0073.png
    - res/cow-anim/frame0074.png
    - res/cow-anim/frame0075.png
    - res/cow-anim/frame0076.png
    - res/cow-anim/frame0077.png
    - res/cow-anim/frame0078.png
    - res/cow-anim/frame0079.png
    - res/cow-anim/frame0080.png
    - res/cow-anim/frame0081.png
    - res/cow-anim/frame0082.png
    - res/cow-anim/frame0083.png
    - res/cow-anim/frame0084.png
    - res/cow-anim/frame0085.png
    - res/cow-anim/frame0086.png
    - res/cow-anim/frame0087.png
    - res/cow-anim/frame0088.png
    - res/cow-anim/frame0089.png
    - res/cow-anim/frame0090.png
    - res/cow-anim/frame0091.png
    - res/cow-anim/frame0092.png
    - res/cow-anim/frame0093.png
    - res/cow-anim/frame0094.png
    - res/cow-anim/frame0095.png
    - res/cow-anim/frame0096.png
    - res/cow-anim/frame0097.png
    - res/cow-anim/frame0098.png
    - res/cow-anim/frame0099.png
    - res/cow-anim/frame0100.png
    - res/cow-anim/frame0101.png
    - res/cow-anim/frame0102.png
    - res/cow-anim/frame0103.png
    - res/cow-anim/frame0104.png
    - res/cow-anim/frame0105.png
    - res/cow-anim/frame0106.png
    - res/cow-anim/frame0107.png
    - res/cow-anim/frame0108.png
    - res/cow-anim/frame0109.png
    - res/cow-anim/frame0110.png
    - res/cow-anim/frame0111.png
    - res/cow-anim/frame0112.png
    - res/cow-anim/frame0113.png
    - res/cow-anim/frame0114.png
    - res/cow-anim/frame0115.png
    - res/cow-anim/frame0116.png
    - res/cow-anim/frame0117.png
    - res/cow-anim/frame0118.png
    - res/cow-anim/frame0119.png
    - res/cow-anim/frame0120.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
